uuidjs/uuid

uuid.js
This small change makes it work perfectly in AMD/CommonJS mixed environments.
=> AMD/CommonJs check swap for AMD+CommonJS mixed environments

uuid.js
MSIE 11 removed support for crypto, renaming their version as msCrypto.
This patch uses window.msCrypto if window.crypto is unavailable (or falls back to the uuid module's RNG).
=> Provide support of MSIE 11 msCrypto

.gitignore, package.json
This pull request adds coverage reporting using [nyc](https://www.npmjs.com/package/nyc):
* run `npm run coverage` to get a human readable coverage report.
* run `npm run coverage -- --reporter=lcov` to get an HTML report over coverage in the /coverage folder.
Here's the current state of things:
```shell
--------------|-----------|-----------|-----------|-----------|
File          |   % Stmts |% Branches |   % Funcs |   % Lines |
--------------|-----------|-----------|-----------|-----------|
./         |     85.05 |     82.28 |     63.64 |     86.54 |
uuid.js |     85.05 |     82.28 |     63.64 |     86.54 |
--------------|-----------|-----------|-----------|-----------|
All files     |     85.05 |     82.28 |     63.64 |     86.54 | …
```
=> add coverage reporting using the nyc bin

uuid.js
This PR fixes an issue we observed with the latest version of node-uuid where it caused crypto-browserify to throw error below when using in a Webpack/Babel environment when trying to run our tests in PhantomJS using Karma.
```
TYPE_MISMATCH_ERR: DOM Exception 17: The type of an object was incompatible with the expected type of
the parameter associated to the object.
```
=> Don't try to load the node package in a browser

lib/sha1.js
Node changed the default from `binary` to `utf8` some time back; this change just specifies `utf8`for older versions of node.
https://nodejs.org/dist/latest-v4.x/docs/api/buffer.html#buffer_class_method_buffer_from_str_encoding
https://nodejs.org/dist/latest-v7.x/docs/api/buffer.html#buffer_class_method_buffer_from_string_encoding
=> specify string encoding of UTF8

.npmignore
This fixes #181 
Personally, I would go one step further and also remove `HISTORY.md` and `AUTHORS` from the packed module. This is obviously up to the owner. I can adjust the PR to include those should that be desired.
=> (fix) Add .npmignore file to exclude test/ and other non-essentials

.gitignore, test/test.js, v5.js
This pull request fixes the `buf` parameter being silently ignored by the code for generating a v5 uuid.
=> Fix buffer not being modified (uuid v5)

.gitignore, README.md, README_js.md, package.json
https://github.com/broofa/runmd is a new module I've been working on that allows you to evaluate JS code blocks in README (and other markdown) files.  Benefits of this:
1. Hooking it into the publish process (via `npm`  'prepare' script hook)  acts as a unit test of sorts.  Publish doesn't happen if the README file can't be built, so there's incentive to insure the README file is kept current.
2. It can automatically inject expression results into the markdown, which makes including expected output in docs easier
3. It forces authors to write code that is accurate and runnable instead of copy/pasting/guessing (**cough** not that I've ever done that.)
Thoughts?
=> Use runmd to build README

README.md, README_js.md
This was previously fixed in https://github.com/kelektiv/node-uuid/commit/880d24e35d2a393b115ce3687465866211ad0680 ,
but was regressed in README_js.md and hence in the newly generated README.md
Also reran `npm run-script prepare` to update README.md from the corrected version
=> Corrected version from v4->v5 in README_js.md

lib/rng-browser.js
getRandomValues needs to be invoked in a context where "this" is a Crypto implementation. Binding the function to its respective Crypto implementation fixes the illegal invocation.
Fixes #256
=> Fix illegal invocation of getRandomValues

CHANGELOG.md, package-lock.json, package.json
Release notes & tag for v3.2.1, to fix #257
@vvo @defunctzombie Can you approve?  I've already `npm publish`ed this (to mitigate number of affected users).  'Just need to merge to master.
[I know publishing before landing on master is probably bad practice, but time seemed of the essence here.  Also, any suggestions for ways to run tests on legacy platforms like IE as part of our CI process?]
=> chore(release): 3.2.1

lib/bytesToUuid.js
Currently, whenever we create an id, we are allocating 600 bytes of memory for each id.
This is because chromium has a bug that does not allow using the '+' operator to allocate memory correctly: https://bugs.chromium.org/p/v8/issues/detail?id=2869
Changing this to a join will fix the size difference:
Concatenate: Shallow Size 40, Retained Size 600
Join: Shallow Size: 64, Retained Size: 64
=> fixed mem issue when generating uuid

lib/v35.js
Replaced assignment to readonly Function.name with Object.defineProperty, as you can't assign to readonly properties in strict mode.
Fixes #268
=> fix assignment to readonly property to allow running in strict mode

lib/rng-browser.js
Users on Windows 7 and IE11 sometimes trigger a bind error because the crypto object exists but getRandomValues is undefined. Using https://github.com/openpgpjs/openpgpjs/pull/207 as a reference, I've added a more robust check for the necessary crypto properties in IE 11.
We deployed our branch into production yesterday. I'll report back in a week to let everyone know if this fixed the issue or not, and if so we can potentially merge?
=> Get correct version of IE11 crypto

src/md5.js, src/sha1.js
BREAKING CHANGE: Remove support for generating v3 and v5 UUIDs in
Node.js<4.x
=> feat: remove support for pre Node.js v4 Buffer API

README.md, README_js.md, examples/browser-umd/README.md, examples/browser-umd/example.html, examples/browser-umd/example.js, examples/browser-umd/package-lock.json, examples/browser-umd/package.json, package-lock.json, package.json, rollup.config.js, scripts/build.sh
A request for this has popped up a number of times in the issues.
I'm still not sure whether I want to add this. It adds another 28kb to the npm package and I'm not sure whether it's worth supporting such a legacy use case.
Plus there are options like https://bundle.run/uuid@latest?name=uuid
What do you think @broofa ?
=> feat: add UMD build to npm package

.github/workflows/browser.yml, .github/workflows/ci.yml, test/browser/edge.test.js
Among all browsers this one seems to be the one who causes almost all
BrowserStack timeouts. Let's remove it and add it again as soon as a
non-beta Chromium Edge version becomes available on BrowserStack.
=> test: remove flaky Edge 79.0 beta test

README.md, README_js.md
@broofa I would like to merge the next branch into master now and revert to trunk-based development. Having the two diverging branches already starts to cause some headache and I would like to avoid that.
I would therefore add a notice to the Readme that points to the current "stable" readme until we release the next major version of this library and then go ahead and merge the `next` branch into `master`.
I would then release the first canary prerelease of the new major version for folks to try out.
I was considering to release it as `v6.0.0` instead of `v4.0.0` in order to avoid any potential confusion around `v3`/`v4`/`v5` uuids.
WDYT?
=> docs: add link to README of stable version

README.md, README_js.md, package.json, test/unit/deep-require-deprecation.test.js, v1.js, v3.js, v4.js, v5.js
=> feat: deprecate deep requires

README.md, README_js.md, package-lock.json, package.json
Especially for use in the browser modern ESModule import syntax is
preferable because it allows for proper treeshaking by bundlers like
Webpack/rollup.
=> docs: prefer esmodule import syntax in README

README.md, README_js.md
As pointed out [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42438#issuecomment-587367163) the version jump from 3.x to 7.x may be confusing to existing users of this library. A short note in the README could help.
=> docs: add note why v7.x follows the v3.x major release

README.md, README_js.md
BREAKING CHANGE: The default export, which used to be the v4() method
but which was already discouraged in v3.x of this library, has been
removed.
Fixes #370
=> docs: add note about removal of default export

README.md, README_js.md
@broofa this would be the last thing I'd merge before doing the 7.0.0 release.
So far we have received a little bit of feedback regarding the new release which was all positive:
- https://github.com/uuidjs/uuid/issues/368#issuecomment-587940059
- https://github.com/uuidjs/uuid/issues/245#issuecomment-587349211
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42438#issuecomment-587437257
Would you prefer to wait a bit longer to collect feedback or just ship 7.0.0?
=> docs: remove link to last stable version

README.md, README_js.md
Did and edit pass on the README.  Specifically:
* Updated the features list at the top
* Moved Quick Start to the top, since that is what most people are going to be interested in.
* Move release notes to the bottom.  Kept a "Upgrading to uuid@3?" line at the top directing people to them, however.
* Renamed all "v3.x"-style uuid version references to "uuid@3" to minimize confusion between RFC UUID "version" and uuid module version.  I.e Don't use "version" to refer to anything but RFC UUID version.
* Unicode warning symbols as html entity char codes (prefer not having actual unicode chars in source).  Also, the "⚠️ ⚠️ ⚠️ ... WARNING HERE ...⚠️ ⚠️ ⚠️" felt a bit excessive. 😄
=> chore: rearrange/edit README

examples/browser-rollup/rollup.config.js, package-lock.json, package.json, rollup.config.js, scripts/build.sh
Probably will fix https://github.com/uuidjs/uuid/issues/378
Currently main field is used for node and module for browser build. This
is not entierly correct. Webpack can be used to build node apps. Though
module is always preferred over main. For browser versions there is a
special field.
In this diff I added esm support for both node and browser.
rollup-plugin-node-resolve look at browser field as well and prefer it
to bundle umd.
=> fix: provide browser versions independent from module system

README.md, README_js.md
Closes #375
This adds information on how to get the library working on React Native to the readme.
-----
I've verified that this works by:
1. creating a new React Native project (`npx react-native init uuidtest`)
2. added the dependencies (`npm add react-native-get-random-values uuid`)
3. imported the polyfill (`import 'react-native-get-random-values'` in `index.js`)
4. and displayed an UUID in the app (`import * as uuid from 'uuid'` and `{uuid.v4()}` in `App.js`)
=> docs: add information on usage from React Native

src/rng-browser.js
It doesn't make sense to explicitly use window. only once in the chain.
=> fix: make access to msCrypto consistent

README.md, README_js.md
I mostly agree with https://github.com/uuidjs/uuid/pull/390#issuecomment-593968052 and that we should not add a huge react native example just for the purpose of documentation.
However I think that we can still make our docs a bit more explicit with respect to how to apply the react native polyfill. I really liked the way nanoid are documenting this in their readme: https://github.com/ai/nanoid#react-native
I am _hoping_ by simply giving these two lines of example code (in the right import order) we can make the lives of react native users easier and reduce the amount of issues raised in this repo from people who just did not go the extra mile to check out the react-native-get-random-values docs.
=> docs: make react native polyfill docs more explicit

README.md, README_js.md
Sorry for the noise. Missed that one in the original commit.
=> docs: directly link to new react-native section

deprecate.js, package.json, v1.js, v3.js, v4.js, v5.js
Relates to #408
I used Node.js' `util.deprecate()` in order to print deprecation warnings for deep requires. This obviously doesn't work in the browser. This can be solved by providing a manual warning fallback for the browser:
=> fix: make deep require deprecation warning work in browsers

.github/workflows/ci.yml, package.json
Always build using the latest supported Node.js version but then run the
CI with all Node.js versions that we want to support.
=> test: always build using Node.js 12.x

.github/workflows/ci.yml, package.json
Instead of using complicated expressions in the package.json scripts
section, rather explicitly specify in the GitHub actions workflow
definitions which scripts should run on which Node.js version.
=> test: run certain parts of ci only on latest Node.js version

README.md, README_js.md
Place the example using `require` as high up in the README as is sensible.
=> Add an example of how to use the module to the README

.babelrc.js, package-lock.json, package.json, v1.js, v3.js, v4.js, v5.js
Since we have deprecated deep requires we no longer need the module.exports from the individual v*.js files.
Since we now ship plain, non-babled deep require files on the top level of the npm package for legacy CommonJS deep-require support we can compensate for the lack of module.exports in there and instead simply access the "default" export of the algorithm-specific modules.
This change was inspired by https://github.com/webpack/webpack/issues/7973#issuecomment-417931938
----
I stumbled upon this one on my struggle to finally make some progress on #402. While this doesn't help with #402 it's certainly no longer necessary and anything we can do to simplify our build pipeline is always welcome I guess.
=> build: remove babel-plugin-add-module-exports

.github/workflows/ci.yml, .local/wrapper.mjs, README.md, README_js.md, examples/node-esmodules/README.md, examples/node-esmodules/example.mjs, examples/node-esmodules/package-lock.json, examples/node-esmodules/package.json, package.json, wrapper.mjs
BREAKING CHANGE: Native ES Modules is still an experimental API in Node.js 14.0.0 and has so far not officially been supported by the `uuid` module.
Since Node.js allows importing CommonJS modules it was possible to import the `uuid` module like this:
```js
import uuid from 'uuid';
console.log(uuid.v4()); // -> 'cd6c3b08-0adc-4f4b-a6ef-36087a1c9869'
```
This will no longer work with proper ES Module exports in place. You can now import the `uuid` library as described in the documentation:
```js
import { v4 as uuidv4 } from 'uuid';
uuidv4(); // ⇨ '9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'
```
or
```js
import * as uuid from 'uuid';
console.log(uuid.v4()); // -> 'cd6c3b08-0adc-4f4b-a6ef-36087a1c9869'
```
Enabling native ES Modules for Node.js requires some special care for the v1 algorithm which …
=> feat: native Node.js ES Modules (wrapper approach)

.github/workflows/ci.yml, .gitignore, package.json, scripts/testpack.sh
Especially for publishing CommonJS/ESM/Browser dual packages a lot can go wrong in the actual build and release step, see: https://medium.com/javascript-in-plain-english/is-promise-post-mortem-cab807f18dcc
In order to catch regressions with respect to the supported ways of importing this library it makes sense to test this using `npm pack`.
Fixes #424
=> test: test imports with npm package contents

examples/benchmark/benchmark.js, src/bytesToUuid.js
I replaced the conversion of bytes to uuid with a more efficient way (and without inflating the size of the resulting string).
Here's what I got in terms of performance.
Benchmark master:
```
uuidv1() x 1,439,640 ops/sec ±0.91% (93 runs sampled)
uuidv1() fill existing array x 7,449,049 ops/sec ±0.55% (90 runs sampled)
uuidv4() x 349,506 ops/sec ±0.88% (90 runs sampled)
uuidv4() fill existing array x 404,741 ops/sec ±1.62% (90 runs sampled)
uuidv3() x 141,296 ops/sec ±0.79% (90 runs sampled)
uuidv5() x 142,066 ops/sec ±0.87% (92 runs sampled)
```
Benchmark this branch:
```
uuidv1() x 1,638,366 ops/sec ±1.07% (92 runs sampled)
uuidv1() fill existing array x 7,837,067 ops/sec ±0.68% (92 runs sampled)
uuidv4() x 394,752 ops/sec ±1.09% (90 runs sampled)
uuidv4() fill existing array x 412,690 …
```
=> feat: improved bytesToUuid func

README_js.md, src/rng.js, src/v4.js, test/unit/v4.test.js
Performance is increased by using a single `rnds8` buffer to generate random numbers (as in browser version).
Changes affect only the `v1` and `v4`.
Benchmark master:
```
uuidv1() x 1,640,551 ops/sec ±0.76% (91 runs sampled)
uuidv1() fill existing array x 7,369,911 ops/sec ±0.49% (96 runs sampled)
uuidv4() x 389,271 ops/sec ±1.39% (92 runs sampled)
uuidv4() fill existing array x 407,681 ops/sec ±1.62% (91 runs sampled)
uuidv3() x 142,615 ops/sec ±0.81% (87 runs sampled)
uuidv5() x 141,386 ops/sec ±1.09% (87 runs sampled)
```
Benchmark this branch:
```
uuidv1() x 1,653,982 ops/sec ±0.91% (90 runs sampled)
uuidv1() fill existing array x 7,383,926 ops/sec ±0.66% (93 runs sampled)
uuidv4() x 471,989 ops/sec ±0.53% (93 runs sampled)
uuidv4() fill existing array x 484,766 ops/sec ±0.48% (96 …
```
=> feat: improved v4 performance

test/unit/v1.test.js, test/unit/v35.test.js
* Simplify the v3/v5 tests for the buffer api
* Add test cases to v1/v3/v5 to ensure that if passing a buffer as
second parameter that buffer is not only filled but also returned. For
v4 this has already been added in #435.
=> test: add tests for buffer api

test/unit/v35.test.js
Although we decided not to accept #439 in its entirety for now, I still wanted to cherry-pick the valuable test improvements.
=> test: improve v3/v5 test

examples/node-commonjs/example.js, examples/node-esmodules/example.mjs, examples/node-esmodules/package.json, package.json, scripts/testpack.sh
It appears that react-native and some bundlers rely on being able to
introspect the package.json file of a npm module. After adding the
`exports` field to package.json, only the paths defined in that field
are accessible to Node.js. In order to support introspection of the
package.json file itself it has to be listed as an export as well (see:
https://github.com/ai/nanoevents/issues/44#issuecomment-602010343).
It is currently being discussed to change Node.js' behavior again, see:
https://github.com/nodejs/node/issues/33460
Fixes #444
=> fix: export package.json required by react-native and bundlers

src/v4.js
In version 1.x of this library it was possible to call `v4('binary')` in
order to receive a byte array instead of a string representation. This
function signature was deprecated in 2.x (but not removed in 3.x as it
should have been).
The correct way to get a binary representation of a uuid is to pass an
array-like object as a second parameter:
```
const buffer = new Array();
v4(null, buffer);
```
Fixes #437.
=> feat: remove deprecated v4 string parameter

.eslintrc.json, examples/benchmark/benchmark.js, src/bytesToUuid.js, src/v1.js
Hello!
I managed to increase the `uuidv1` generation performance by replacing `[]` to `new Array(16)`.
I also added an error code when throwing an exception for exceeding `v1` generation limit per second.
I would like to add error codes to all your exceptions. To make it easier to identify the error by its code (instead of a message).
But we need to work on the names of the error codes. We need to standardize names (or somewhere to look).
If at all you like the idea with error codes =)
If not, then I can remove them.
Benchmark master:
```
uuidv1() x 1,634,946 ops/sec ±0.82% (90 runs sampled)
uuidv1() fill existing array x 7,727,514 ops/sec ±0.63% (92 runs sampled)
uuidv4() x 449,289 ops/sec ±0.63% (95 runs sampled)
uuidv4() fill existing array x 463,831 ops/sec ±0.70% (92 runs sampled) …
```
=> feat: slightly improved v1 perf

README.md, README_js.md
=> docs: document cdnjs usage

CHANGELOG.md, LICENSE.md, README.md, README_js.md, prettier.config.js
I no longer want to try to achieve consistent line lengths in markdown
so I'd prefer prettier to do that for me.
=> chore: add proseWrap prettier config to wrap markdown

bundlewatch.config.json, examples/browser-webpack/package-lock.json, examples/browser-webpack/package.json, examples/browser-webpack/webpack.config.js, examples/node-webpack/package-lock.json, examples/node-webpack/package.json, examples/node-webpack/webpack.config.js, package.json
=> Prepare package exports for webpack 5

wdio.conf.js
Browserstack seems to have trouble accessing the local proxy on recent
Edge 18.0 / Windows 10 machines. Since Edge 18.0 is deprecated anyways
and since we still have an Edge 15.0 test as a safety net it should be
fine to just drop the Edge 18.0 test.
=> test: remove flaky Edge 18.0 on Windows 10 test

README.md, README_js.md
Thanks to pkg.exports this module is now well-supported by
https://jspm.org/ without any Node.js crypto api polyfills for the
browser.
/cc @guybedford
=> docs: document jspm usage

wdio.conf.js
With the added tests IE11 tests have become flaky since they simply seem
too sloooooooooooow. The tests in IE11 take up to 1:30 to run while they
usually finish after around 30s in all other browsers.
=> test: increase wdio timout

examples/benchmark/package-lock.json, package-lock.json, package.json
TBH dependabot is such a shitshow. Bothering us about irrelevant minor security flaws in dev dependencies, that, upon each merge to master, cause 3 pull-requests to be auto-rebased, overwhelming our Browserstack instance, leading to timeouts for tests on master, which I then have to re-run manually.
I have disabled dependabot and I suggest to leave it disabled as long as this library doesn't have any production dependencies.
Or am I missing something?
=> chore: run npm audit fix to satisfy dependabot

wdio.conf.js
Wdio executes tests in order. We have 5 concurrent execution slots at
BrowserStack. Since the IE tests take by far the longest time (1:30
instead of 0:30 for all others) it makes sense to run them first. Safari
tests seem to execute the fastes, so run them last.
=> test: optimize browser test order

README.md, README_js.md
The new APIs are introduced in 8.3, not 8.2.
=> docs: fix readme with respect to new api version

src/rng.js
* Significantly improves v4 performance for the default RNG by introducing batch generation
Benchmark `master` (bc9d4eda7dafce60d503435f09e7cbb0c7384d18):
```
uuidv1() x 1,868,914 ops/sec ±0.26% (92 runs sampled)
uuidv1() fill existing array x 9,711,758 ops/sec ±0.16% (94 runs sampled)
uuidv4() x 412,330 ops/sec ±0.13% (98 runs sampled)
uuidv4() fill existing array x 513,285 ops/sec ±0.16% (93 runs sampled)
uuidv3() x 321,397 ops/sec ±0.57% (91 runs sampled)
uuidv5() x 301,932 ops/sec ±1.08% (90 runs sampled)
Fastest is uuidv1() fill existing array
```
Benchmark this branch (pool size 64):
```
uuidv1() x 1,800,216 ops/sec ±0.80% (96 runs sampled)
uuidv1() fill existing array x 9,679,788 ops/sec ±0.27% (95 runs sampled)
uuidv4() x 819,473 ops/sec ±0.37% (96 runs sampled)
uuidv4() fill …
```
=> perf(nodejs): introduce pool into default rng

README.md, README_js.md
Thanks to
https://github.com/LinusU/react-native-get-random-values/pull/13 Expo
finally has support for a sync CSPRNG.
Fixes #375
=> feat: support expo>=39.0.0

src/rng-browser.js
Here's a PR for the lazy loading fix discussed in #536. This defers the loading and caching of crypto.getRandomValues to first invocation, rather than module load time, helping out React Native clients.
Without this change, RN projects must manage an implicit dependency on react-native-get-random-values, and try to ensure that it gets loaded before uuid does.
With this change, the RN polyfill simply needs to be installed sometime before the first uuid is created.
No significant benchmark differences. (In fact the v4 tests ran slightly faster on my machine with this change, but I'm sure that was accidental.)
=> lazy-load getRandomValues to mitigate problems with react-native-get-random-values polyfill

README.md, README_js.md
Created in lieu of specific per-version validation methods as seen in https://github.com/uuidjs/uuid/pull/542
Might be something stupid I'm doing but for some reason, having the two aliased imports caused `SyntaxError: Cannot use import statement outside a module`
=> docs: add examples of per-version validation

src/v35.js
Frameworks like Next.js complain about anonymous export default functions, e.g.
`Anonymous function declarations cause Fast Refresh to not preserve local component state.`
Versions beside 3.5 already use named exports, so update 3.5 to do the same.
=> Change default export to named function

README.md, README_js.md
It's very convenient and wonderful to be able to use uuid generation on the command line!
I think that it is convenient to use in npx.
```
$ uuid
ddeb27fb-d9a0-4624-be4d-4615062daed4
```
```
$ npx uuid
ddeb27fb-d9a0-4624-be4d-4615062daed4
```
=> docs: add command 'npx' for CLI usage

README.md, README_js.md
Updates the README as it had a broken link with an extra x at the end.
=> fix: upgrading from uuid3 broken link

test/unit/validate.test.js
=> chore: validate() tests for invalid NIL uuids

.husky/commit-msg, .husky/pre-commit, package.json
fix broken husky hooks. (caused by https://github.com/uuidjs/uuid/pull/585 by upgrading v4 to v7)
=> chore: fix husky v7 hooks

bundlewatch.config.json, package.json, src/native-browser.js, src/native.js, src/v4.js, wdio.conf.js
*Before:*
```
uuidv4() x 2,232,325 ops/sec ±0.12% (95 runs sampled)
uuidv4() fill existing array x 8,398,262 ops/sec ±0.16% (97 runs sampled)
```
*After:*
```text
uuidv4() x 25,076,827 ops/sec ±1.93% (96 runs sampled)
uuidv4() fill existing array x 8,407,653 ops/sec ±0.21% (97 runs sampled)
```
This uses the native `crypto.randomUUID` if available, which results in more than an **11x** speedup on Node.js v16.11.1 on my M1 MacBook Air. All this while only increasing the bundle size with **34 bytes**!
The patch implements my changes described here: https://github.com/uuidjs/uuid/pull/555#issuecomment-770720130
Closes #555
=> feat: use native crypto.randomUUID when available

babel.config.json
This change is a noop with respect to the build, it yields the exact same output files (tested by building with and without this patch and running `diff -r dist-node-8 dist-node-10` which yields an empty result).
=> Support only node 10

src/stringify.js, src/v1.js, src/v35.js, src/v4.js, test/unit/stringify.test.js
It turns out that validation in `uuidStringify()` is slowing it down by 33x. Since  `uuidv1()` and `uuidv4()` produce valid buffers by the virtue of their algorithm they can safely use a validation-free version of stringify.
`uuidv1()` - faster by **1.3x**
`uuidv4()` - faster by **4.3x**
the gains are due to `.unsafeStringify()` with no validation (as it is not required) is 33x faster than the version with validation.
The public `uuidStringify()` has been left unchanged but my recommendation would be to also remove validation from this method in the future and just export the unsafe version.
```
uuidStringify() x 2,957,961 ops/sec ±0.78% (86 runs sampled)
uuidParse() x 3,331,671 ops/sec ±0.59% (93 runs sampled)
---
uuidv1() x 3,185,198 ops/sec ±0.54% (91 runs sampled)
uuidv1() fill …
```
=> chore: optimize uuid.v4 by 4.3x (430%) (internal stringify by 33x)

examples/node-esmodules/example.mjs, examples/node-esmodules/package.json, examples/node-esmodules/package.mjs, scripts/testpack.sh
While ESM support has been stable in current versions of Node.js 14.x and 16.x, support for importing JSON files is still experimental and evolving.
Since we still want to cover the fact that the package is exporting it's package.json file, this test is now extracted to only run with the updated JSON import syntax which requires import assertions and which was introduced in Node.js 16.14.0.
Fixes #619
=> chore: run node-esmodule package.json test only in latest node LTS

src/v35.js, test/unit/v35.test.js
=> fix: handle error when parameter is not set in v3 and v5

README.md, README_js.md, babel.config.json, src/rng-browser.js, wdio.conf.js
Closes #469
After adjusting the babel preset-env targets the browser build only changed with respect to `let/const` vs. `var` usage, see [this diff](https://gist.github.com/ctavan/519360f8777905838a9398b534e530ad#file-browser-build-diff).
It all still works in IE11 🤷‍♂️ .
I could break IE11 support by removing the `msCrypto` special case in: https://github.com/uuidjs/uuid/blob/c9e076c852edad7e9a06baaa1d148cf4eda6c6c4/src/rng-browser.js#L18-L20
On the other hand those 3 lines don't really hurt…
So the question is now whether we want to be even more aggressive with respect to browser support?
The next step we could go would be to allow function default parameters (equivalent to moving `firefox 51 -> 53` and `edge 14 -> 15`), which would add [this …
=> Drop IE 11 support

examples/node-jest/package-lock.json, examples/node-jest/package.json
Cleaner than using an `alpha` 🙂
=> chore: use stable Jest 29 in tests

README.md, README_js.md
BREAKING CHANGE: This library always aims at supporting one EOLed LTS release
which by this time now is 12.x which has reached EOL 30 Apr 2022.
The actual change was already introduced in #643 but the commit was missing the
breaking change label.
=> chore: drop node 10.x to upgrade dev dependencies

.github/FUNDING.yml, package.json
Enables the "Sponsor this project" sidebar.
I honestly don't know if this will generate any actual sponsorships, but I'd like to try it out just to see what happens.  I expect this'll be more useful for the insight it brings into how [in]effective github is as a source of revenue for opensource developers than anything else.
@ctavan: 'Doesn't look like you're setup to take sponsorships on Github, but I'm happy to add you to this of course.  I'm open to suggestions for adding others, but looking at the "contributors", I think you and I are the two most obvious candidates here.
=> chore: add FUNDING.yml, fixes #384

src/stringify.js
From the discussion and experimentation in #676 I found that we are running `toLowerCase` on every generated id instead of once when constructing `byteToHex`.
In fact, `toString(16)` seems to already return lower case, but I cannot be sure that this is guaranteed by the spec after reading it, and since it doesn't do any harm I kept it:
https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-numeric-types-number-tostring
`npm run test:benchmark` is returning some strange results though:
Name | Before change | After change
---- | ------------- | ------------
uuid.stringify() | x 4,494,323 ops/sec ±0.14% | x 3,529,389 ops/sec ±0.13%
uuid.parse() | x 4,021,155 ops/sec ±0.05% | x 4,015,847 ops/sec ±0.06%
uuid.v1() | x 4,612,946 ops/sec ±0.18% | x 6,409,517 ops/sec ±0.12% …
=> perf: remove superfluous call to toLowerCase

README.md, README_js.md
=> docs: add note about `cypto.randomUUID()`

README.md, README_js.md, package-lock.json, package.json, scripts/build.sh
Fix broken image for RunMD
The image that was linked to from the README.md file was broken in imgur. I replaced the URL to the correct one from GitHub
=> Replace broken image in README file

.github/SECURITY.md, README_js.md
Minimal SECURITY.md file, as requested in 696 just to get something up.  'Figure we can flesh this out further later, as needed.
=> chore: add SECURITY.md, fixes #696

README.md, README_js.md, test/unit/parse.test.js
Took a quick pass with cSpell. These were the only ones that looked off.
=> chore: minor typos in non-code areas

.github/workflows/browser.yml, .github/workflows/ci.yml
`pull_request_target` allows runs to access the secret values. Since this adds an attack vector described here https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ I added the extra condition to only run on the main repo `push` or if someone adds a `safe to test` label after reviewing the code
=> ci: run browser tests on pull_request_target

package-lock.json
NPM was complaining about a high severity vulnerabilty after running install. Autofixed with `npm audit fix` to update the lockfile
=> chore: run npm audit fix for json5

src/stringify.js
This reverts commit e53793f5be93413cad68b05b3a339ca23e993342 per [this discussion](https://github.com/uuidjs/uuid/pull/677#issuecomment-1757351351)
=> fix: revert "perf: remove superfluous call to toLowerCase (#677)"

src/md5.js, src/native.js, src/rng.js, src/sha1.js
Cloudflare Workers/Pages work with certain native node libraries (https://developers.cloudflare.com/workers/runtime-apis/nodejs) but for them to work correctly they need to be imported with `node:crypto` instead of `crypto` (for example).
This PR updates `uuid` so it imports from `node:crypto` to resolve this issue.
=> build: use node:crypto not crypto when importing

package.json
This makes it clear which package manager we're using.
=> chore: enable corepack w/ npm

CHANGELOG.md, package-lock.json, package.json
Manually edited the CHANGELOG to include "uuid v7" PR.
@pmccarren @ctavan: This is the last step before `npm publish`.  Speak now or hold your peace. :-)
=> chore(release): 10.0.0

src/v7.js, test/unit/v7.test.js
A typo that fits just right in the rfc example blind spot.
=> fix(v7): seq_hi shift for byte 6

README.md, README_js.md
Updating README for `v11` release.
- Added verbiage to alert readers to the breaking changes (`options` handling, byte array types)
- Removed old verbiage about past bugs and issues prior to v9. (This stuff took up a lot of space and only applied to a vanishingly small contingent of readers.)
- Update examples to use `Uint8Array` type instead of `Array`s.
=> docs: update README for v11

src/test/v4.test.ts, src/v4.ts
This removes the v4 options default assignment introduced during porting to ts (by mistake maybe?), during https://github.com/uuidjs/uuid/pull/763 - [PR diff](https://github.com/uuidjs/uuid/pull/763/files#diff-d7d9279b5eb8b7335eff565ca2e9a7e9ec8ff7d7de248197ce80481c118ea5de) - [commit](https://github.com/uuidjs/uuid/commit/1e0f9870db864ca93f7a69db0d468b5e1b7605e7#diff-d7d9279b5eb8b7335eff565ca2e9a7e9ec8ff7d7de248197ce80481c118ea5de) preventing `native.randomUUID` from being used
if `options` always have a value, we will never enter the if in line 11. `{}`  will be assigned to `options` in line 15 after the native check
it looks to me that the line 9 statement is added by mistake
=> fix: remove v4 options default assignment preventing native.randomUUID from being used

eslint.config.mjs
IE11 / `msCrypto` was removed with release v9.
=> fix: remove obsolete code for removed IE11 support

.github/workflows/release-please.yml
'Think I found the problem with the RP workflow not running the `npm  publish` steps: The `release-please-action` step was missing an `id`, meaning `steps.release.outputs.release_created` wasn't getting set properly.
=> chore: add id to RP workflow step

.github/workflows/browser.yml
=> chore: update to actions/checkout@v4

src/v1.ts, src/v3.ts, src/v4.ts, src/v5.ts, src/v6.ts, src/v7.ts
The `v4` function is guaranteed to return a string unless the `buf` argument is provided. By modifying the signature to denote this parameter as required for the `Uint8Array` case, we get the benefit of a stricter return type of `string` when simply calling `v4()`.
=> fix: apply stricter typing to the v* signatures

src/v3.ts, src/v5.ts
As @robbtraister [notes](https://github.com/uuidjs/uuid/pull/831#issuecomment-2455326219), these overloads are necessary to indicate the different return types.
=> fix: revert "simplify type for v3 and v5"

README.md, README_js.md
=> docs: add notes on platform support

README.md, README_js.md
I came across what I believe is a typo. `Insure` is sometimes an alternate spelling of `ensure` although it appears that's an archaic variant. Feel free to close without merging if you prefer the alternate spelling. 
https://en.wiktionary.org/wiki/insure
https://en.wiktionary.org/wiki/ensure
=> fix(docs): insure -> ensure

README.md, README_js.md
When using on React Native, there is a link shown, https://github.com/uuidjs/uuid#getrandomvalues-not-supported, if the polyfill react-native-get-random-values is not installed. However, this link's anchor is not working because the title in the README has changed.
The React Native info was removed in b08c122248950db0df371c79638e0c5ffe3d6726 and re-added in ae8f38657bca0ee053bf29c88c006b1ea05af1b5, but the heading was changed so this link was broken.
This patch re-adds that anchor so the link points the user to proper spot in the README.
=> docs: Ensure link to getrandomvalues-not-supported is maintained

.github/ISSUE_TEMPLATE/bug_report.yml, .vscode/extensions.json, CONTRIBUTING.md, README.md, README_js.md
* #841 fix
* #863 fix
* Update `buffer` type in README
* Long overdue update to CONTRIBUTING
=> docs: docs housecleaning

src/test/parse.test.ts, src/test/rng.test.ts, src/test/stringify.test.ts, src/test/v1.test.ts, src/test/v35.test.ts, src/test/v4.test.ts, src/test/v6.test.ts, src/test/v7.test.ts, src/test/validate.test.ts, src/test/version.test.ts, src/uuid-bin.ts
Just some test-related improvements I thought would be nice to contribute.
Node's assert module:
* Use protocol import (prefixed with `node:`).
* Use [strict assertion mode](https://nodejs.org/api/assert.html#strict-assertion-mode) (import from `node:assert/strict`).
Node's test runner:
* Import `test` as a named import, rather than a default import.
=> refactor: improve imports for the Node assert and test modules

.github/workflows/browser.yml, .github/workflows/ci.yml
Potential fix for [https://github.com/uuidjs/uuid/security/code-scanning/5](https://github.com/uuidjs/uuid/security/code-scanning/5)
To fix the issue, we will add a `permissions` block at the root level of the workflow file. This block will explicitly define the permissions for the `GITHUB_TOKEN`. Since the workflow primarily involves linting, testing, and documentation checks, it does not require write permissions. Therefore, we will set `contents: read` as the minimal required permission. This change will apply to all jobs in the workflow.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> chore(ci): add workflow permissions

.github/workflows/ci.yml
Adding node@24 to CI matrix.
Per our support policy we could drop node@16 but that'll require a major version bump, which I'm not interested in doing at this time.  We can do that and update the supported `tsc` version at a future date.
fixes #877
=> feat: add node@24 to ci matrix

package-lock.json, package.json
Updating as part of the 12.x release.  Our policy for typescript is to support releases up to two years back. `5.2.2` was released 2023-08-24T16:38:15.233Z, so I'll hold off on publishing the 12.x release (that includes this) until 2025-08-24.
See also #856
=> feat!: update to typescript@5.2

README_js.md, src/md5.ts, src/native.ts, src/rng.ts, src/sha1.ts
=> fix: restore node: prefix
