uuid.js
This lib should probably be tested on various platforms to make sure it's actually crypto random as expected.
See https://github.com/broofa/node-uuid/issues/122
=> fix node.js security vulnerability

package.json
Updated license info according to [npm](https://docs.npmjs.com/files/package.json#license) documentation.
=> Fix license info

README.md
I think you meant that part to be displayed as bold :)
=> Correct bold

.travis.yml
PR opened to trigger a test run against 0.12.
=> Test against still-supported 0.12.

.eslintrc.json, README.md, lib/bytesToUuid.js, lib/rng-browser.js, lib/rng.js, lib/sha1-browser.js, lib/sha1.js, package.json, test/test.js, v1.js, v5.js
Here's the v5 code I've been noodling on.
I'm comfortable with the API, and it works in node (via `npm test`), but I haven't done any in-browser testing.  There's also room for performance improvements, as currently I convert the namespace strings to byte arrays on every call, which is less than ideal, but I have limited time to work on this.  I think we can deal with that later, if it ever becomes an issue people care about.
=> V5 support

CHANGELOG.md, package-lock.json, package.json
@defunctzombie I'd like to push a new release to address #318 
Bumps the version.  Bumps package dependencies to fixup npm audit issues.  And  goes back to explicit version declarations in package.json.
=> V3.3.3 prep

CHANGELOG.md, package.json, v1.js
=> feat: rename repository to github:uuidjs/uuid

v1.js, v3.js, v4.js, v5.js
Updated the links to point to the intended section in the README file.
=> fix: update links to match content in readme

README.md, README_js.md
=> chore: add webworker to not supported table 

README.md, README_js.md, src/uuid-bin.js, src/v35.js, src/v4.js, test/unit/v35.test.js
Some changes from #455 that I'd like to see in master.
/cc @awwit
=> chore: improve code style

CHANGELOG.md, CONTRIBUTING.md, LICENSE.md, README.md, README_js.md, prettier.config.js
This basically does the opposite of d5ce415363fcf3f9caab56b2d8a17f341ba51889
=> chore: set prettier proseWrap to never

README.md, README_js.md
=> Add Browser passing action to README file.

.github/ISSUE_TEMPLATE/bug_report.md
See if we can encourage users to provide better examples by adding a party-popper checkbox that lets them confirm they've actually read and understand the SO page on what a good example looks like.
=> chore: improved bug report template

.github/ISSUE_TEMPLATE/bug_report.md
Since people tend to never provide minimal reproducible examples I want
to make this a strict requirement for bug reports.
=> chore: require minimal reproducible example for bugs

README.md, README_js.md
=> docs: be explicit about react native import order

README.md, README_js.md
=> Fix typo in readme

.github/workflows/stale-issues.yml
This has been failing with the following error message for a while:
```
The workflow is not valid. .github/workflows/stale-issues.yml (Line: 20,
Col: 32): A sequence was not expected .github/workflows/stale-issues.yml
(Line: 21, Col: 29): A sequence was not expected
```
=> chore: upgrade and fix the stale-issues workflow

test/unit/rng.test.js
=> test: remove missing getRandomValues test

.github/workflows/ci.yml, README.md, README_js.md
=> chore: add node@12 back in, update readme

examples/browser-rollup/package-lock.json, examples/browser-webpack/package-lock.json, test/browser/browser.spec.js
=> fix: missing v7 expectations in browser spec

.prettierignore
release-please's edits to CHANGELOG.md cause `prettier` to complain so... ignoring.
=> chore: ignore changelog when linting

README.md, README_js.md, package-lock.json, package.json
Updating packages.  Mostly doing this to pick up https://github.com/broofa/runmd/pull/31 in `runmd`, which should fix the "disagreement" that `runmd` and `prettier` have over formatting that's preventing the the checks in #845 from passing.
=> chore: update packages
